# -*- coding: utf-8 -*-
"""Spark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JEWiPv2yi0HKho0ST1LObgYiVw8vsI3G
"""

# Install Java
!apt-get install openjdk-11-jdk-headless -qq > /dev/null

# Install PySpark
!pip install pyspark --quiet

# Optional: install findspark
!pip install findspark --quiet

import os

!apt-get update -qq
!apt-get install openjdk-17-jdk -qq > /dev/null

# Find the actual Java path
import subprocess
result = subprocess.run(['update-alternatives', '--list', 'java'], capture_output=True, text=True)
print(result.stdout)

# Step 1: Update package index first
!apt-get update -qq

# Step 2: Then install Java
!apt-get install openjdk-11-jdk-headless -qq

import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"

import findspark
findspark.init()

# Set JAVA_HOME — adjust path if Cell 1 showed a different version
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-17-openjdk-amd64"
os.environ["PATH"] = os.environ["JAVA_HOME"] + "/bin:" + os.environ["PATH"]

# Verify it works
!java -version
!echo $JAVA_HOME

!pip install pyspark -q

from pyspark.sql import SparkSession
spark= SparkSession.builder\
.appName("Prcatice Spark Session")\
.master("local[*]") \
.getOrCreate()

print(spark.version)

data= [("Alice",34),("Max",25),("Jordan",26),("John",24)]
columns=["Name","Age"]
df=spark.createDataFrame(data,columns)
df.show()

from pyspark.sql.functions import col
df.filter(col("Age")>25).show()

# add a column
df.withColumn("Age after 10 years", col("Age")+10).show()

# sorting a columns
df.sort(col("Age"),ascending=True).show()

df.createOrReplaceTempView("People")
query=spark.sql("SELECT * FROM people where Age>=30")
query.show()

# reading a csv
df_csv= spark.read.csv("/content/sample_data/california_housing_train.csv", header= True, inferSchema=True)
df_csv.printSchema()
df_csv.show()